import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import ServiceWorkerRegistration from "@/components/global/ServiceWorkerRegistration";

import { Providers } from "@/app/providers";
import { Layout } from "@/components/global/village-ds";

import { Main } from "@/components/global/village-ds";
import { Toaster } from "@/components/ui/sonner";

import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout className={`${geistSans.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Main className="mt-24">{children}</Main>
          <Toaster />
          <ServiceWorkerRegistration />
        </Providers>
      </body>
    </Layout>
  );
}
